### ISSUE TITLE
get annoto settings validation

### ISSUE THREAD

**Issue by genadis** [Annoto/xblock-in-video-collaboration#10]
When getting the settings, add sanity checks:

1. strip trailing spaces.
2. if clientid is provided make sure secret is provided as well. (if clientid is not provided it's ok for checking out Annoto in demoMode, then secret can be empty, but not if clientid is provided).
2. validate that clientId is valid JWT if it is provided.

https://github.com/Annoto/xblock-in-video-collaboration/blob/master/annoto/annoto.py#L126

**Comment by Marx86** [comment]
How should the exception handling take place?
If you want to an error shown  in the "advanced settings", then it is impossible.

**Comment by genadis** [comment]
@Marx86 What are the options then?
can error be shown when adding the Annoto module in the course?

**Comment by genadis** [comment]
Fixed by https://github.com/Annoto/xblock-in-video-collaboration/pull/12
