### ISSUE TITLE
Meaningful course id

### ISSUE THREAD

**Issue by genadis** [Annoto/xblock-in-video-collaboration#7]
To obtain the course id string: [`self.course_id.to_deprecated_string()`](https://github.com/Annoto/xblock-in-video-collaboration/blob/master/annoto/annoto.py#L100) is used.

Is this optimal? based on:
https://github.com/edx/edx-platform/wiki/Opaque-Keys-(Locators)
https://course-catalog-api-guide.readthedocs.io/en/latest/intro_edx_apis.html

1. Can the course id be used in the openEdx API?
2. Can the the catalog ID be obtained based on the courseID?

**Comment by Marx86** [comment]
Method "to_deprecated_string" returns the new stile string, like "course-v1:edX+DemoX.1+2014".
All APIs where used <course_id> should be works with this ID.

**Comment by genadis** [comment]
@Marx86 
Just to be sure, the [openEdx catalog api course_id](https://course-catalog-api-guide.readthedocs.io/en/latest/intro_edx_apis.html) is the one obtained via `to_deprecated_string`?

* is there a way to obtain the catalog ID based on this courseID? or do we must extract it in the xBlock alongside the course_id? If there is no way, it makes sense to extract it in the xblock and to use `[CATALOG_ID]__[COURSE_ID]` as the group id provided to Annoto. If it can be extracted via course_id and the catalog API can be used using only the course_id then there is no need.

**Comment by Marx86** [comment]
"edx-platform" is not providet this API, it seems that this is a commercial API of edx.org
